services:
  postgres:
    image: postgres:17-alpine
    container_name: oustadi-db-dev
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oustadi
      POSTGRES_USER: oustadi
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: oustadi-redis-dev
    restart: unless-stopped
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  maildev:
    image: maildev/maildev:latest
    container_name: oustadi-maildev
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080

volumes:
  postgres_data_dev:
  redis_data_dev:
