FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY . .
RUN pnpm install
RUN cd apps/web && npx next build
EXPOSE 3000
CMD cd apps/web && npx next start -p 3000
