FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY . .
RUN pnpm install
RUN cd apps/api && npx prisma generate
RUN pnpm --filter @oustadi/api run build
EXPOSE 3000
CMD ["node", "apps/api/dist/main.js"]
